version: '3'


services:
  zookeeper:
    image: confluent/zookeeper

  kafka:
    image: confluent/kafka
    links:
      - zookeeper:zookeeper

  riemann:
    image: riemannio/riemann
    volumes:
      - ./riemann.config:/etc/riemann.config

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - 5601:5601
  program:
    build:
      context: .
